apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  secret-key: {{ .Values.secrets.secretKey | quote }}
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  admin-username: {{ .Values.secrets.adminUsername | quote }}
  admin-password: {{ .Values.secrets.adminPassword | quote }}
