apiVersion: v1
kind: Service
metadata:
  name: {{ include "solarwatch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: solarwatch
    component: web
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: solarwatch
    component: web
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
