"""Startup validation and bootstrap logic.

Same design as the Flask template: linear, readable checks that run once at
startup via FastAPI's lifespan context. If any step fails the app still starts
but all routes (except /health) return 503 until the issue is resolved.

Insert new steps at the bottom of STARTUP_STEPS to extend the sequence.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from typing import Callable, List

from sqlalchemy import text
from werkzeug.security import generate_password_hash

from app.db import get_connection

LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True)
class StartupStep:
    name: str
    handler: Callable[[], List[str]]


def _validate_required_env_vars() -> List[str]:
    """Ensure all required environment variables are present."""
    errors: List[str] = []

    for key in ("APP_ADMIN_USERNAME", "APP_ADMIN_PASSWORD"):
        if not os.getenv(key):
            errors.append(f"Missing required environment variable: {key}")

    has_database_url = bool(os.getenv("DATABASE_URL"))
    db_parts = ["DB_HOST", "DB_PORT", "DB_USER", "DB_PASSWORD", "DB_NAME"]
    has_db_parts = all(os.getenv(p) for p in db_parts)
    if not (has_database_url or has_db_parts):
        errors.append(
            "Missing database config. Provide DATABASE_URL or set "
            "DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME."
        )

    secret_key = os.getenv("SECRET_KEY")
    if not secret_key or secret_key == "change-me":
        errors.append("SECRET_KEY must be set to a non-default value.")

    return errors


def _verify_database_connectivity() -> List[str]:
    try:
        with get_connection() as conn:
            conn.execute(text("SELECT 1"))
    except Exception as exc:
        return [f"Database connection failed: {exc}"]
    return []


def _ensure_foundational_tables() -> List[str]:
    """Create roles and web_users tables if they do not exist.

    Schema is intentionally identical to the Flask template so the same
    Postgres database can be shared between both templates during a migration.
    """
    try:
        with get_connection() as conn:
            conn.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS roles (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name TEXT NOT NULL UNIQUE,
                        description TEXT,
                        is_system BOOLEAN NOT NULL DEFAULT FALSE,
                        enabled BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            conn.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS web_users (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username TEXT NOT NULL UNIQUE,
                        password TEXT NOT NULL,
                        role_id INTEGER NOT NULL REFERENCES roles(id),
                        enabled BOOLEAN NOT NULL DEFAULT TRUE,
                        must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            # Safe migration for databases created before must_change_password existed.
            conn.execute(
                text(
                    """
                    ALTER TABLE web_users
                    ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE
                    """
                )
            )
    except Exception as exc:
        return [f"Failed to ensure foundational tables: {exc}"]
    return []


def _ensure_system_roles() -> List[str]:
    try:
        with get_connection() as conn:
            existing = {
                row["name"]
                for row in conn.execute(
                    text("SELECT name FROM roles WHERE name IN ('admin', 'user')")
                ).mappings()
            }
            for role_name, description in (
                ("admin", "Full administrative access"),
                ("user", "Standard authenticated user"),
            ):
                if role_name in existing:
                    conn.execute(
                        text(
                            "UPDATE roles SET is_system = TRUE, enabled = TRUE WHERE name = :name"
                        ),
                        {"name": role_name},
                    )
                else:
                    conn.execute(
                        text(
                            """
                            INSERT INTO roles (name, description, is_system, enabled)
                            VALUES (:name, :description, TRUE, TRUE)
                            """
                        ),
                        {"name": role_name, "description": description},
                    )
    except Exception as exc:
        return [f"Failed to ensure system roles: {exc}"]
    return []


def _ensure_admin_user() -> List[str]:
    username = os.getenv("APP_ADMIN_USERNAME")
    password = os.getenv("APP_ADMIN_PASSWORD")
    if not username or not password:
        return ["APP_ADMIN_USERNAME and APP_ADMIN_PASSWORD must be set."]

    reset_password = os.getenv("APP_ADMIN_RESET_PASSWORD", "false").lower() in {
        "true", "1", "yes"
    }

    try:
        with get_connection() as conn:
            admin_role = conn.execute(
                text("SELECT id FROM roles WHERE name = 'admin'")
            ).mappings().first()
            if not admin_role:
                return ["Admin role missing; cannot provision admin user."]

            existing = conn.execute(
                text("SELECT id FROM web_users WHERE username = :username"),
                {"username": username},
            ).mappings().first()

            if existing:
                if reset_password:
                    LOGGER.warning(
                        "Admin password reset requested via APP_ADMIN_RESET_PASSWORD."
                    )
                    conn.execute(
                        text(
                            """
                            UPDATE web_users
                            SET role_id = :role_id,
                                enabled = TRUE,
                                password = :password,
                                must_change_password = TRUE
                            WHERE id = :user_id
                            """
                        ),
                        {
                            "role_id": admin_role["id"],
                            "password": generate_password_hash(password),
                            "user_id": existing["id"],
                        },
                    )
                else:
                    conn.execute(
                        text(
                            "UPDATE web_users SET role_id = :role_id, enabled = TRUE WHERE id = :user_id"
                        ),
                        {"role_id": admin_role["id"], "user_id": existing["id"]},
                    )
            else:
                conn.execute(
                    text(
                        """
                        INSERT INTO web_users
                            (username, password, role_id, enabled, must_change_password)
                        VALUES (:username, :password, :role_id, TRUE, TRUE)
                        """
                    ),
                    {
                        "username": username,
                        "password": generate_password_hash(password),
                        "role_id": admin_role["id"],
                    },
                )
    except Exception as exc:
        return [f"Failed to ensure admin user: {exc}"]
    return []


STARTUP_STEPS: List[StartupStep] = [
    StartupStep("Validate required environment variables", _validate_required_env_vars),
    StartupStep("Verify database connectivity", _verify_database_connectivity),
    StartupStep("Ensure foundational tables exist", _ensure_foundational_tables),
    StartupStep("Ensure system roles exist", _ensure_system_roles),
    StartupStep("Ensure admin user exists", _ensure_admin_user),
]


def run_startup_checks() -> List[str]:
    """Run all startup steps and return a flat list of errors."""
    errors: List[str] = []
    for step in STARTUP_STEPS:
        step_errors = step.handler()
        if step_errors:
            errors.extend(f"{step.name}: {e}" for e in step_errors)
    return errors
